### ISSUE TITLE
Supernova crashes on dedicated servers

### ISSUE THREAD

**Issue by WinDanesz** [WinDanesz/mo-spells#6]

**Comment by WinDanesz** [comment]
```
java.lang.NoSuchMethodError: com.bobmowzie.mowziesmobs.server.damage.DamageUtil.dealMixedDamage(Lnet/minecraft/entity/EntityLivingBase;Lnet/minecraft/util/DamageSource;FLnet/minecraft/util/DamageSource;F)Lorg/apache/commons/lang3/tuple/Pair;
    at com.windanesz.mospells.entity.EntityMagicSuperNova.onUpdate(EntityMagicSuperNova.java:85)
    at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1996)
    at net.minecraft.world.World.updateEntity(World.java:1958)
    at net.minecraft.world.World.redirect$updateEntity$zbn000(World.java:4623)
    at net.minecraft.world.World.updateEntities(World.java:1762)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1847)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1098)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


```
